name: Pack

on: [push]

jobs:
  pack-examples:
    name: Pack examples

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [12.x]

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: cd examples && npm ci

    - name: Pack
      run: cd examples && npm run pack

    - name: Archive examples package artifacts
        uses: actions/upload-artifact@v1
        with:
          name: examples
          path: examples/dist
