name: Lint and test code (cross-platform)

on: [push]

jobs:

  run:
    name: Run

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [8.x, 10.x, 12.x]

    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm test
